# Generated by Django 5.0.6 on 2024-06-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_name', models.CharField(max_length=50)),
                ('Recipe_description', models.TextField()),
                ('Recipe_image', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
